"""initial schema

Revision ID: 196aaea3c545
Revises: 
Create Date: 2026-08-21 02:12:47.214127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '196aaea3c545'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('reminded', sa.Boolean(), nullable=False),
    sa.Column('completed_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category', 'tasks', ['category'], unique=False)
    op.create_index('idx_completed', 'tasks', ['completed'], unique=False)
    op.create_index('idx_deadline', 'tasks', ['deadline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_deadline', table_name='tasks')
    op.drop_index('idx_completed', table_name='tasks')
    op.drop_index('idx_category', table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
